import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/NavBar";
import LenisSmoothScroll from "@/components/Animation/LenisScroll";
import Loader from "@/components/Loader/Loader";


const PPNeueMontreal = localFont({
  src: [
    { path: "../../public/assets/fonts/PPNeueMontreal-Regular.woff2", weight: "400", style: "normal" },
    { path: "../../public/assets/fonts/PPNeueMontreal-Medium.woff2", weight: "500", style: "normal" },
    { path: "../../public/assets/fonts/PPNeueMontreal-SemiBold.woff2", weight: "600", style: "normal" },
    { path: "../../public/assets/fonts/PPNeueMontreal-Bold.woff2", weight: "700", style: "normal" },
  ],
  variable: "--font-PPNeueMontreal",
  display: "swap",
  fallback: ["system-ui, sans-serif"],
});

export const metadata = {
  title: "Intertia Studio | Creative Studio",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/favicon.png" },
    ],
    apple: [
      { url: "/favicon.png" },
    ],
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${PPNeueMontreal.variable} antialiased`}
      >
        <LenisSmoothScroll />
        <Loader />
        {children}
      </body>
    </html>
  );
}
